"""New view about bots!_4

Revision ID: 201c0c5079c1
Revises: 85ac1d26358e
Create Date: 2025-02-09 10:26:45.917920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201c0c5079c1'
down_revision: Union[str, None] = '85ac1d26358e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PricesTable', sa.Column('time_frame', sa.String(), nullable=False))
    op.drop_column('PricesTable', 'symbol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PricesTable', sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('PricesTable', 'time_frame')
    # ### end Alembic commands ###
