"""New view about bots!

Revision ID: 22afd93d7797
Revises: 2b8ca59a4ad3
Create Date: 2025-02-08 21:51:46.122576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22afd93d7797'
down_revision: Union[str, None] = '2b8ca59a4ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoinsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LevelsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('Level', sa.Float(), nullable=False),
    sa.Column('Mother_date', sa.JSON(), nullable=False),
    sa.Column('Mother_prices', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PricesTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Open', sa.Float(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=False),
    sa.Column('High', sa.Float(), nullable=False),
    sa.Column('Low', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('BTCUSDT_charact')
    op.drop_table('BTCUSDT_table_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BTCUSDT_charact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('BTCUSDT_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relative_height_30', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('relative_low_30', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('relative_height_20', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('relative_low_20', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('relative_height_10', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('relative_low_10', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('relative_height_5', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('relative_low_5', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('relative_height_1', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('relative_low_1', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['BTCUSDT_id'], ['BTCUSDT_table_day.id'], name='BTCUSDT_charact_BTCUSDT_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='BTCUSDT_charact_pkey')
    )
    op.create_table('BTCUSDT_table_day',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('Open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('Close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('High', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('Low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='BTCUSDT_table_day_pkey')
    )
    op.drop_table('PricesTable')
    op.drop_table('LevelsTable')
    op.drop_table('CoinsTable')
    # ### end Alembic commands ###
