"""изменение таблицы 2

Revision ID: 2b8ca59a4ad3
Revises: 527a0ab79d6b
Create Date: 2024-12-29 13:00:10.793175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8ca59a4ad3'
down_revision: Union[str, None] = '527a0ab79d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BTCUSDT_table_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Open', sa.Float(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=False),
    sa.Column('High', sa.Float(), nullable=False),
    sa.Column('Low', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BTCUSDT_charact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BTCUSDT_id', sa.Integer(), nullable=False),
    sa.Column('relative_height_30', sa.Boolean(), nullable=False),
    sa.Column('relative_low_30', sa.Boolean(), nullable=False),
    sa.Column('relative_height_20', sa.Boolean(), nullable=False),
    sa.Column('relative_low_20', sa.Boolean(), nullable=False),
    sa.Column('relative_height_10', sa.Boolean(), nullable=False),
    sa.Column('relative_low_10', sa.Boolean(), nullable=False),
    sa.Column('relative_height_5', sa.Boolean(), nullable=False),
    sa.Column('relative_low_5', sa.Boolean(), nullable=False),
    sa.Column('relative_height_1', sa.Boolean(), nullable=False),
    sa.Column('relative_low_1', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['BTCUSDT_id'], ['BTCUSDT_table_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BTCUSDT_charact')
    op.drop_table('BTCUSDT_table_day')
    # ### end Alembic commands ###
