"""New view about bots!_2

Revision ID: 51f39b796108
Revises: 22afd93d7797
Create Date: 2025-02-08 22:58:45.115509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f39b796108'
down_revision: Union[str, None] = '22afd93d7797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PricesTable', sa.Column('id_coin', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'PricesTable', 'CoinsTable', ['id_coin'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PricesTable', type_='foreignkey')
    op.drop_column('PricesTable', 'id_coin')
    # ### end Alembic commands ###
