"""писание изменения

Revision ID: 527a0ab79d6b
Revises: 
Create Date: 2024-12-29 11:40:03.642002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '527a0ab79d6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BTCUSDT_table_day', sa.Column('Date', sa.DateTime(), nullable=True))
    op.add_column('BTCUSDT_table_day', sa.Column('Open', sa.Float(), nullable=True))
    op.add_column('BTCUSDT_table_day', sa.Column('Close', sa.Float(), nullable=True))
    op.add_column('BTCUSDT_table_day', sa.Column('High', sa.Float(), nullable=True))
    op.add_column('BTCUSDT_table_day', sa.Column('Low', sa.Float(), nullable=True))
    op.drop_column('BTCUSDT_table_day', 'close_prise')
    op.drop_column('BTCUSDT_table_day', 'low_prise')
    op.drop_column('BTCUSDT_table_day', 'height_prise')
    op.drop_column('BTCUSDT_table_day', 'date')
    op.drop_column('BTCUSDT_table_day', 'open_prise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BTCUSDT_table_day', sa.Column('open_prise', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('BTCUSDT_table_day', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('BTCUSDT_table_day', sa.Column('height_prise', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('BTCUSDT_table_day', sa.Column('low_prise', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('BTCUSDT_table_day', sa.Column('close_prise', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('BTCUSDT_table_day', 'Low')
    op.drop_column('BTCUSDT_table_day', 'High')
    op.drop_column('BTCUSDT_table_day', 'Close')
    op.drop_column('BTCUSDT_table_day', 'Open')
    op.drop_column('BTCUSDT_table_day', 'Date')
    # ### end Alembic commands ###
