"""Добавление 4

Revision ID: 5fd1cfd76156
Revises: d87fd2c747e6
Create Date: 2025-03-04 10:26:21.358526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd1cfd76156'
down_revision: Union[str, None] = 'd87fd2c747e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserLevelsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_coin', sa.Integer(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('Level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_coin'], ['CoinsTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserLevelsTable')
    # ### end Alembic commands ###
