"""Initial tables

Revision ID: 636f1f4a18b1
Revises: 
Create Date: 2025-03-26 14:09:37.213899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636f1f4a18b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoinsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('HideLevelsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_coin', sa.Integer(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('Level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_coin'], ['CoinsTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LevelsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_coin', sa.Integer(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('Level', sa.Float(), nullable=False),
    sa.Column('Mother_date', sa.JSON(), nullable=False),
    sa.Column('Mother_prices', sa.JSON(), nullable=False),
    sa.Column('Source', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id_coin'], ['CoinsTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PricesTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_coin', sa.Integer(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Open', sa.Float(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=False),
    sa.Column('High', sa.Float(), nullable=False),
    sa.Column('Low', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_coin'], ['CoinsTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PriorityLevelsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_coin', sa.Integer(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('Level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_coin'], ['CoinsTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserLevelsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_coin', sa.Integer(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('Level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_coin'], ['CoinsTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserLevelsTable')
    op.drop_table('PriorityLevelsTable')
    op.drop_table('PricesTable')
    op.drop_table('LevelsTable')
    op.drop_table('HideLevelsTable')
    op.drop_table('CoinsTable')
    # ### end Alembic commands ###
