"""Миграция сайта 1

Revision ID: 75acff9eaeda
Revises: 7fcb1b2f5e3e
Create Date: 2025-02-28 22:34:07.477120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75acff9eaeda'
down_revision: Union[str, None] = '7fcb1b2f5e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
