"""New view about bots!_8

Revision ID: 7fcb1b2f5e3e
Revises: e3c43d731a5a
Create Date: 2025-02-14 15:27:43.705040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcb1b2f5e3e'
down_revision: Union[str, None] = 'e3c43d731a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LevelsTable', sa.Column('Source', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LevelsTable', 'Source')
    # ### end Alembic commands ###
