"""New view about bots!_5

Revision ID: a9363570b972
Revises: 201c0c5079c1
Create Date: 2025-02-09 11:24:38.291316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9363570b972'
down_revision: Union[str, None] = '201c0c5079c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'CoinsTable', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CoinsTable', type_='unique')
    # ### end Alembic commands ###
