"""Добавление 3

Revision ID: d87fd2c747e6
Revises: 744c7a2c39c8
Create Date: 2025-03-03 20:34:16.798816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87fd2c747e6'
down_revision: Union[str, None] = '744c7a2c39c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HideLevelsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_coin', sa.Integer(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('Level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_coin'], ['CoinsTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HideLevelsTable')
    # ### end Alembic commands ###
