"""New view about bots!_7

Revision ID: e3c43d731a5a
Revises: f956b31a1f25
Create Date: 2025-02-14 15:15:35.018478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c43d731a5a'
down_revision: Union[str, None] = 'f956b31a1f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LevelsTable', sa.Column('id_coin', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'LevelsTable', 'CoinsTable', ['id_coin'], ['id'])
    op.drop_column('LevelsTable', 'symbol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LevelsTable', sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'LevelsTable', type_='foreignkey')
    op.drop_column('LevelsTable', 'id_coin')
    # ### end Alembic commands ###
